services:
  cleo:
    build:
      context: ..
      dockerfile: deploy/cleo/Dockerfile-cleo
    environment:
      CLEO_URL_FILE: /run/secrets/cleo_url
      CLEO_USER_FILE: /run/secrets/cleo_user
      CLEO_PW_FILE: /run/secrets/cleo_pw
      CLEO_PROJECT_FILE: /run/secrets/cleo_project
      SENDER_SERVER_FILE: /run/secrets/sender_server
      SENDER_PORT_FILE: /run/secrets/sender_port
      SENDER_REPLYTO_FILE: /run/secrets/sender_replyto
      SENDER_USER_FILE: /run/secrets/sender_user
      SENDER_PW_FILE: /run/secrets/sender_pw
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
    secrets:
      - cleo_url
      - cleo_user
      - cleo_pw
      - cleo_project
      - sender_server
      - sender_port
      - sender_replyto
      - sender_user
      - sender_pw
      - openai_api_key
    volumes:
      - a2rchi-data:/root/data/

  chat:
    build:
      context: ..
      dockerfile: deploy/chat/Dockerfile-chat
    environment:
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
    secrets:
      - openai_api_key
    volumes:
      - a2rchi-data:/root/data/

  mailbox:
    build:
      context: ..
      dockerfile: deploy/mailbox/Dockerfile-mailbox
    environment:
      IMAP_USER_FILE: /run/secrets/imap_user
      IMAP_PW_FILE: /run/secrets/imap_pw
      CLEO_URL_FILE: /run/secrets/cleo_url
      CLEO_USER_FILE: /run/secrets/cleo_user
      CLEO_PW_FILE: /run/secrets/cleo_pw
      CLEO_PROJECT_FILE: /run/secrets/cleo_project
      SENDER_SERVER_FILE: /run/secrets/sender_server
      SENDER_PORT_FILE: /run/secrets/sender_port
      SENDER_REPLYTO_FILE: /run/secrets/sender_replyto
      SENDER_USER_FILE: /run/secrets/sender_user
      SENDER_PW_FILE: /run/secrets/sender_pw
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
    secrets:
      - imap_user
      - imap_pw
      - cleo_url
      - cleo_user
      - cleo_pw
      - cleo_project
      - sender_server
      - sender_port
      - sender_replyto
      - sender_user
      - sender_pw
      - openai_api_key

  # TODO: do mailbox, chat service, or cleo need ports open?
  # ports:
  #   - "8000:8000"

  scraper:
    build:
      context: ..
      dockerfile: deploy/scraper/Dockerfile-scraper
    volumes:
      - a2rchi-data:/root/data/

volumes:
  a2rchi-data:
    external: true

secrets:
  imap_user:
    file: imap_user.txt
  imap_pw:
    file: imap_pw.txt
  cleo_url:
    file: cleo_url.txt
  cleo_user:
    file: cleo_user.txt
  cleo_pw:
    file: cleo_pw.txt
  cleo_project:
    file: cleo_project.txt
  sender_server:
    file: sender_server.txt
  sender_port:
    file: sender_port.txt
  sender_replyto:
    file: sender_replyto.txt
  sender_user:
    file: sender_user.txt
  sender_pw:
    file: sender_pw.txt
  openai_api_key:
    file: openai_api_key.txt
