name: grading_test

global:
  TRAINED_ON: "problem 1 rubric"

locations_of_secrets:
  - ~/.secrets/api_tokens
  - ~/.secrets/salts_and_internal_passwords
  - ~/.secrets/grader

chains:
  input_lists:
    - configs/submit.list
    - configs/miscellanea.list
  chain:
    IMAGE_PROCESSING_MODEL_NAME: HuggingFaceImageLLM
    GRADING_FINAL_GRADE_MODEL_NAME: HuggingFaceOpenLLM
    MODEL_CLASS_MAP:
      HuggingFaceOpenLLM:
        kwargs:
          base_model: "Qwen/Qwen2.5-7B-Instruct-1M"
          quantization: True
          enable_salesforce_content_safety: false
      HuggingFaceImageLLM:
        kwargs:
          base_model: "Qwen/Qwen2.5-VL-7B-Instruct"
          quantization: True
          enable_salesforce_content_safety: false

  prompts:
    IMAGE_PROCESSING_PROMPT: configs/prompts/image_processing.prompt
    GRADING_FINAL_GRADE_PROMPT: configs/prompts/grading_final_grade.prompt

utils:
  data_manager:
    chromadb_external_port: 8002
  embeddings:
    EMBEDDING_NAME: HuggingFaceEmbeddings
    EMBEDDING_CLASS_MAP:
      HuggingFaceEmbeddings:
        similarity_score_reference: 10
interfaces:
  grader_app:
    HOSTNAME: "submit76.mit.edu"
    num_problems: 1
