name: prod_submit

global:
  TRAINED_ON: "the SubMIT Cluster"  

locations_of_secrets:
  - ~/.secrets/api_tokens
  - ~/.secrets/salts_and_internal_passwords
  - ~/.secrets/submit_cleo_and_mailer_passwords

chains:
  input_lists:  
    - configs/submit.list
    - configs/miscellanea.list
  chain:
    MODEL_NAME: OpenAIGPT35
    CONDENSE_MODEL_NAME: OpenAIGPT35
    SUMMARY_MODEL_NAME: OpenAIGPT35
  prompts:
    CONDENSING_PROMPT: configs/prompts/condense.prompt  
    MAIN_PROMPT: configs/prompts/submit.prompt  
    SUMMARY_PROMPT: configs/prompts/summary.prompt  

interfaces:
  chat_app:
    PORT: 7861
    EXTERNAL_PORT: 7861
    HOSTNAME: "t3desk019.mit.edu"
  
